site_name: SimplyMap Documentation
theme:
  name: material
  features:
    - content.code.copy
    - content.code.highlight
    - content.code.annotate  # Enables language labels for code blocks
nav:
    - Home: index.md
    - Usage: usage.md
    - API Reference: api.md
    - Server Setup: server.md  # Added link to server.md
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true  # Ensure line numbers are enabled
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
